config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :portfolios, exept: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'about', to: 'pages#About'
  get 'contact', to: 'pages#Contact'
  resources :blogs
  root to: 'pages#Home' 
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord


	validates_presence_of :title, :body
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.page(params[:page]).per(params[:per_page])
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def Home
  	@posts = Blog.all
  	@skills = Skill.all
  end

  def About
  end

  def Contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
	def index
		@portfolio_items = Portfolio.all		
	end

	def new
		@portfolio_item = Portfolio.new
	end

	def create
    @portfolio_item = Portfolio.new(params.require(:portfolio).permit(:title,:subtitle, :body))

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Your portfolio has been created' }
        format.json { render :show, status: :created, location: @portfolio_item }
      else
        format.html { render :new }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end


def edit
	@portfolio_item = Portfolio.find(params[:id])
end

def update
	@portfolio_item = Portfolio.find(params[:id])
    respond_to do |format|
      if @portfolio_item.update(params.require(:portfolio).permit(:title,:subtitle, :body))
        format.html { redirect_to portfolios_path, notice: 'Portfolio Item was successfully updated.' }
        
      else
        format.html { render :edit }
        
      end
    end
  end

def show
   @portfolio_item = Portfolio.find(params[:id]) 
end

def destroy
  @portfolio_item = Portfolio.find(params[:id]) 
  @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_path, notice: 'Portfolio Item was successfully destroyed.' }
      
    end
  
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_blog.html.erb
<div class="blog-post">
      <h2 class="blog-post-title"><%=link_to blog.title.upcase, blog %></h2>
      <p class="blog-post-meta">Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</a></p>
      <p>
      	<%= blog.body %>
      </p>
         <%= link_to 'Edit', edit_blog_path(blog)%></a>
         <%= link_to 'New', new_blog_path(blog)%></a>
         <%= link_to 'Delete Post', blog, method: :delete, data: { confirm: 'Are you sure?'}%></a>
     <br>
     <br>
     <br>
     <br>
   
</div>

app/views/blogs/_form.html.erb
<%#= form_with(model: blog, local: true) do |form| %>
  <div class="form-group">
 <%= simple_form_for @blog do |f| %>

  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


 
    <%= f.label :title  %>
    <%= f.text_field :title , class:"form-control" %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body , class:"form-control" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
	
	<%= paginate @blogs %>


    <%= render @blogs %>
   <br>
   <br> 


    <%= paginate @blogs %>

    

app/views/blogs/new.html.erb
<h1>New Blog</h1>


<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

	<p>
	<strong>Title:</strong>
	<%= @blog.title %>
	</p>

	<p>
	<%= @blog.body %>
	</p>

	<%= link_to 'Edit', edit_blog_path(@blog) %> | <%= link_to 'Back', blogs_path %>
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>My First Website</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <%= render "shared/application_nav"%>
   
          
          <%= yield %>
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p> 
          <%= render "shared/application_footer" %>
    </div>
  
  </body>
</html>

app/views/layouts/blogs.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>My First Website</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'blog', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <main role="main" class="container">
      <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <%= render "shared/application_nav"%>
              <div class="row">
                <div class="col-md-9 blog-main">
                       <%= yield %>
                </div>        
                          
                      <aside class="col-md-3 blog-sidebar">
                        
                        <div class="p-3">
                          <h4 class="font-italic">Archives</h4>
                          <ol class="list-unstyled mb-0">
                            <li><a href="#">March 2014</a></li>
                            <li><a href="#">February 2014</a></li>
                            <li><a href="#">January 2014</a></li>
                            <li><a href="#">December 2013</a></li>
                            <li><a href="#">November 2013</a></li>
                            <li><a href="#">October 2013</a></li>
                            <li><a href="#">September 2013</a></li>
                            <li><a href="#">August 2013</a></li>
                            <li><a href="#">July 2013</a></li>
                            <li><a href="#">June 2013</a></li>
                            <li><a href="#">May 2013</a></li>
                            <li><a href="#">April 2013</a></li>
                          </ol>
                        </div>

                        <div class="p-3">
                          <h4 class="font-italic">Elsewhere</h4>
                          <ol class="list-unstyled">
                            <li><a href="#">GitHub</a></li>
                            <li><a href="#">Twitter</a></li>
                            <li><a href="#">Facebook</a></li>
                          </ol>
                        </div>
                      </aside><!-- /.blog-sidebar -->

                

                <p class="notice"><%= notice %></p>
                <p class="alert"><%= alert %></p> 
                
              </div><!-- /.row -->
              <%= render "shared/application_footer" %> 
      </div>

    </main><!-- /.container -->
  
       
  
  </body>
</html>

app/views/pages/About.html.erb
<main role="main" class="inner cover">
  <h1 class="cover-heading">About Page</h1>
  <p>Find me in app/views/pages/About.html.erb</p>
</main>

app/views/pages/Contact.html.erb
<main role="main" class="inner cover">
  <h1 class="cover-heading">Contact Page</h1>
  <p>Find me in app/views/pages/Contact.html.erb</p>
</main>

app/views/pages/Home.html.erb
<main role="main" class="inner cover">
    <h1 class="cover-heading">Cover your page.</h1>
    <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
    <p class="lead">
      <%= link_to "About Me", about_path, class: "btn btn-lg btn-secondary" %>
    </p>
  </main>

  

app/views/portfolios/edit.html.erb
<h1>Edit Portfolio Item</h1>

<%= form_with(model: @portfolio_item, local: true) do |form| %>
  
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>
  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>
  <br>
  <br>
  <br>
  <p><%= link_to "Create New Item", new_portfolio_path %></p>
	  
		<% @portfolio_items.each do |portfolio_item| %>

				<p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
				<p><%=portfolio_item.subtitle%></p>
				<p><%=portfolio_item.body%></p>
				<p><%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %></p>
				<%= link_to 'Delete Portfolio Item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %>

<% end %>

app/views/portfolios/new.html.erb
<h1>Create a new Portfolio Item</h1>

<%= form_with(model: @portfolio_item, local: true) do |form| %>
  
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>
  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_item.main_image %>
<h1><%= @portfolio_item.title %></h1>
<em><%= @portfolio_item.subtitle %></em>

<p><%= @portfolio_item.body %></p>

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
    <div class="inner ">
      <p>All rights reserved <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
    </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
   <h3 class="masthead-brand"><p style="font-weight:900;">Lorenzo Palazzina</p></h3>
   <nav class="nav nav-masthead justify-content-center">
       <%= link_to "Home", root_path, class: 'nav-link' %>
       <%= link_to "Blog", blogs_path, class: 'nav-link' %>
       <%= link_to "About", about_path, class: 'nav-link' %>
       <%= link_to "Contact", contact_path, class: 'nav-link' %>
       <%= link_to "PortFolios", portfolios_path, class: 'nav-link' %>
       
       
      <% if current_user %>
        <%= link_to "Logout", destroy_user_session_path, class: 'nav-link' %>
        <%= link_to "Edit user", edit_user_registration_path, class: 'nav-link' %>
      <% else %>
        <%= link_to "Register", new_user_registration_path, class: 'nav-link' %> 
        <%= link_to "Login", new_user_session_path, class: 'nav-link' %>
      <% end %>
   </nav>
  </div>
</header>  